name: Github Pages

on:
  push:
    branches:
    - dev  # default branch

PUBLISH_BRANCH: master  # deploying branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.10.0
      with:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: dev
        PUBLISH_DIR: ./dist